default_context:
  project_name: 'conflux'
  project_slug: 'conflux'
  domain_main: 'conflux.bio'
  domain_staging: 'stag.conflux.bio'
  docker_swarm_stack_name_main: 'conflux-bio'
  docker_swarm_stack_name_staging: 'stag-conflux-bio'
  secret_key: '662fc79479107a08bf22f68c8ffa4f657b419a57bb79504084f66b66c3b6c621'
  first_superuser: 'admin@conflux.bio'
  first_superuser_password: 'S0lveEtCoagula'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.conflux.bio", "https://stag.conflux.bio", "https://conflux.bio", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@conflux.bio'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@conflux.bio'
  pgadmin_default_user_password: 'S0lveEtCoagula'
  traefik_constraint_tag: 'conflux.bio'
  traefik_constraint_tag_staging: 'stag.conflux.bio'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:S0lveEtCoagula'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
